name: parcel_track
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  hive_flutter: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  page_transition: ^2.1.0
  country_picker: ^2.0.26
  flutter_form_builder: ^9.3.0
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^11.0.0
  intl: ^0.19.0
  pinput: ^5.0.0
  carousel_slider: ^5.0.0
  riverpod_annotation: ^2.3.5
  google_maps_flutter: ^2.9.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.4.0
  location: ^7.0.1
  permission_handler: ^11.3.1
  animated_toggle_switch: ^0.8.3
  intl_utils: ^2.8.7
  url_launcher: ^6.3.0
  html: ^0.15.4
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.4
  open_file_plus: ^3.4.1+1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/svgs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf

flutter_intl:
  enabled: true
